### ISSUE TITLE
database如何连接

### ISSUE THREAD

**Issue by riddle911** [lovetheory/nkc2#28]
这块是吴局负责吗。
问一下，我已经安装完成，网页访问1086端口显示的500错误，报错信息是database没有连接。
我在server_settings里只找到定义 nkc这个数据库名，没有发现类似数据库的用户名和口令的选项。
求助一下，这块是怎么做
谢谢~

**Comment by lzszone** [comment]
那个文件没有好久没更新了，可能需要自己改动一下，npm搜arangojs或者官网有教程。。。

**Comment by lzszone** [comment]
@riddle911 需要在server_settings里面定义一个arango对象
```
settings.arango={
  url: 'http://root:@127.0.0.1:8529', //默认是这样的.
  databaseName: '数据库名字',    //数据库名称
  arangoVersion: 20800 //如果你是用是3.0版本以下的数据库,那加上这句.
};

**Comment by riddle911** [comment]
报告~添加了您的代码，也参考了arangojs的demo。
感觉没毛病。但还是报错
抛出的错误
‘request to path / encountered an error. If you think this shouldn't happen, please contact the Site Admin.
UnauthorizedError: Unauthorized
    at /home/user/nkc2/node_modules/arangojs/lib/connection.js:167:44
    at callback (/home/user/nkc2/node_modules/arangojs/lib/util/request.js:50:12)
    at IncomingMessage.<anonymous> (/home/user/nkc2/node_modules/arangojs/lib/util/request.js:58:11)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)’

**Comment by lzszone** [comment]
@riddle911 在server_settings里面 settings.urlrewrite里面替换下面几个对象试试：
```
  {map: '/', to: '/api/operation?&operation=viewHome'},
  {map: /^\/\?(.*)/, to: '/home$1'},
  {map: /^\/home\??(.*)/, to: '/api/operation?&operation=viewHome$1'},
  {map:'/index',to:'/'},
```
大概在110行左右

**Comment by riddle911** [comment]
昂 最近工作忙  没来及折腾。我回头试下 谢政哥~
