### ISSUE TITLE
What kind of open source license does this project use?

### ISSUE THREAD

**Issue by celeron533** [lovetheory/nkc2#60]
> License
You are allowed to use these files for any purpose. The author of these files shall not be held responsible for any terrorist attacks or global climate changes caused by the use of these files.

Is it GPL, LGPL, Apache, MIT or other?
https://choosealicense.com/

**Comment by lzszone** [comment]
a ISC License is declared at /package.json before I take over it so I know nothing... and we may change it to another one later
