### ISSUE TITLE
SMS verification whether it can support the United States?

### ISSUE THREAD

**Issue by kslr** [lovetheory/nkc2#70]
+1 etc..

**Comment by lzszone** [comment]
Seem to be no...
We use Ali-dayu as our sms service which is a third-party offered service ,
I've read it's document, no overseas support is mentioned.
Are you in abroad?
If you have any trouble with the verification...I can take a meesage to the Admin...

**Comment by kslr** [comment]
Okay, I used China Phone Verification.
If there is better... :)
